/**
 * Provenance and caveats. Static prose — the numbers live in the data
 * modules, generated by the Python pipeline in this repo.
 */

export default function AboutView() {
  return (
    <main className="view about">
      <section>
        <h2>What this is</h2>
        <p>
          Every NBA draft of the two-round era — 1989 to today — in two
          views: the lottery as it actually unfolded (the odds each team
          carried in, the order the drawing produced, who jumped and who
          fell), and the full draft board with what every pick became over
          an NBA career.
        </p>
      </section>

      <section>
        <h2>Where the data comes from</h2>
        <p>
          Lottery odds, chances, and results are parsed from{' '}
          <a href="https://www.thedraftreview.com" rel="noreferrer noopener" target="_blank">
            The Draft Review
          </a>
          &apos;s lottery history pages. Draft picks, colleges, drafting
          teams, and career statistics come from NBA Stats via{' '}
          <a href="https://github.com/swar/nba_api" rel="noreferrer noopener" target="_blank">
            nba_api
          </a>
          . The two sources are cross-checked in the harvest pipeline: the
          player listed at each lottery position must match that draft&apos;s
          pick at the same slot, and any disagreement fails the build.
        </p>
      </section>

      <section>
        <h2>How the lottery has changed</h2>
        <ul>
          <li>
            <strong>1989</strong> — unweighted: every non-playoff team had an
            equal shot at No. 1.
          </li>
          <li>
            <strong>1990–1993</strong> — weighted with 66 chances split by
            inverse record; top three picks drawn.
          </li>
          <li>
            <strong>1994–2018</strong> — the 1,000-combination machine,
            tightened after Orlando won from 1.5% in 1993; top three picks
            drawn.
          </li>
          <li>
            <strong>2019–</strong> — flattened odds (the three worst records
            share 14.0%) and the top four picks drawn.
          </li>
        </ul>
      </section>

      <section>
        <h2>Caveats</h2>
        <ul>
          <li>
            Forfeited picks are simply absent, so some drafts have fewer than
            60 selections and some lotteries fewer teams than the era
            standard.
          </li>
          <li>
            The lottery table shows the team that held the pick on lottery
            night and the player taken at that slot; picks are often traded,
            before and after the drawing.
          </li>
          <li>
            Career totals are NBA regular season only — no playoffs, no
            other leagues.
          </li>
        </ul>
      </section>
    </main>
  )
}
