"""Generate the site's committed data modules from the harvested CSVs.

Reads  data/lottery.csv, data/draft_history.csv, data/careers.csv,
       data/career_totals.csv, output/{colleges,teams,steals,pick_curve}.csv
Writes src/data/lottery.js, src/data/drafts.js, src/data/analysis.js

The CSVs are the source of truth (the analysis phase reads them from Python
and R); these JS modules are a derived, deterministic re-expression so the
site renders with zero runtime requests. Output is stable across runs: rows
are emitted in (year, position) order with a fixed key order.

Career files may be absent while the careers harvest is still running; the
generator then emits career: null for every pick and says so, and is simply
re-run once 03 finishes.

Run: .venv/bin/python python/04_generate_site_data.py
"""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
ANALYSIS = ROOT / "output"
OUT = ROOT / "src" / "data"

BANNER = "// GENERATED by python/04_generate_site_data.py — do not edit by hand.\n"


def opt_float(s: str) -> float | None:
    return float(s) if s else None


def opt_int(s: str) -> int | None:
    return int(s) if s else None


def load_lottery() -> list[dict]:
    by_year: dict[int, list[dict]] = defaultdict(list)
    with (DATA / "lottery.csv").open() as f:
        for r in csv.DictReader(f):
            record = (f"{r['record_w']}-{r['record_l']}"
                      if r["record_w"] else None)
            by_year[int(r["year"])].append({
                "resultPos": int(r["result_position"]),
                "team": r["team"],
                "record": record,
                "oddsPct": opt_float(r["odds_pct"]),
                "chances": opt_int(r["chances"]),
                "seed": int(r["pre_lottery_seed"]),
                "delta": int(r["seed_delta"]),
                "player": r["player_picked"],
            })
    return [{"year": y, "teams": sorted(rows, key=lambda t: t["resultPos"])}
            for y, rows in sorted(by_year.items())]


def load_careers() -> dict[int, dict] | None:
    totals_path = DATA / "career_totals.csv"
    seasons_path = DATA / "careers.csv"
    if not totals_path.exists() or not seasons_path.exists():
        return None
    seasons: dict[int, list[str]] = defaultdict(list)
    teams: dict[int, list[str]] = defaultdict(list)
    with seasons_path.open() as f:
        for r in csv.DictReader(f):
            pid = int(r["PLAYER_ID"])
            if r["SEASON_ID"] not in seasons[pid]:
                seasons[pid].append(r["SEASON_ID"])
            abbr = r["TEAM_ABBREVIATION"]
            if abbr and abbr != "TOT" and abbr not in teams[pid]:
                teams[pid].append(abbr)
    careers: dict[int, dict] = {}
    with totals_path.open() as f:
        for r in csv.DictReader(f):
            pid = int(float(r["PLAYER_ID"]))
            careers[pid] = {
                "gp": int(float(r["GP"])),
                "min": int(float(r["MIN"] or 0)),
                "pts": int(float(r["PTS"])),
                "seasons": len(seasons[pid]),
                "teams": teams[pid],
            }
    return careers


def load_drafts(careers: dict[int, dict] | None) -> list[dict]:
    by_year: dict[int, list[dict]] = defaultdict(list)
    with (DATA / "draft_history.csv").open() as f:
        for r in csv.DictReader(f):
            pid = int(r["PERSON_ID"])
            by_year[int(r["SEASON"])].append({
                "overall": int(r["OVERALL_PICK"]),
                "round": int(r["ROUND_NUMBER"]),
                "roundPick": int(r["ROUND_PICK"]),
                "player": r["PLAYER_NAME"],
                "personId": pid,
                "team": f"{r['TEAM_CITY']} {r['TEAM_NAME']}".strip(),
                "org": r["ORGANIZATION"],
                "orgType": r["ORGANIZATION_TYPE"],
                "career": careers.get(pid) if careers else None,
            })
    return [{"year": y, "picks": sorted(rows, key=lambda p: p["overall"])}
            for y, rows in sorted(by_year.items())]


def load_table(name: str, int_cols: set[str],
               float_cols: set[str]) -> list[dict]:
    with (ANALYSIS / f"{name}.csv").open() as f:
        rows = []
        for r in csv.DictReader(f):
            rows.append({k: (int(v) if k in int_cols else
                             float(v) if k in float_cols else v)
                         for k, v in r.items()})
        return rows


def write_module(path: Path, banner_lines: str) -> None:
    path.write_text(BANNER + banner_lines)
    print(f"wrote {path}")


def js(value) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)

    lottery = load_lottery()
    write_module(OUT / "lottery.js", (
        f"export const LOTTERY = {js(lottery)}\n"
        "export const LOTTERY_BY_YEAR = "
        "Object.fromEntries(LOTTERY.map((s) => [s.year, s]))\n"
        "export const LOTTERY_YEARS = LOTTERY.map((s) => s.year)\n"))

    careers = load_careers()
    if careers is None:
        print("careers CSVs not present yet — emitting career: null "
              "(re-run after python/03_harvest_careers.py completes)")
    drafts = load_drafts(careers)
    write_module(OUT / "drafts.js", (
        f"export const DRAFTS = {js(drafts)}\n"
        "export const DRAFTS_BY_YEAR = "
        "Object.fromEntries(DRAFTS.map((d) => [d.year, d.picks]))\n"
        "export const DRAFT_YEARS = DRAFTS.map((d) => d.year)\n"))

    # Analysis tables come from python/05_analyze.py (reconciled against R);
    # absent tables just mean 05 hasn't run yet.
    if not (ANALYSIS / "colleges.csv").exists():
        print("analysis tables not present yet — skipping analysis.js "
              "(re-run after python/05_analyze.py)")
        return 0
    colleges = load_table("colleges", {"draftees", "hits"},
                          {"hit_rate", "total_min", "value_added"})
    teams = load_table("teams", {"picks", "hits"},
                       {"avg_pick", "total_min", "expected_min",
                        "value_added"})
    steals = load_table("steals", {"year", "pick"},
                        {"career_min", "expected_min", "value_added"})
    curve = load_table("pick_curve", {"picks"}, {"mean_min"})
    write_module(OUT / "analysis.js", (
        "export const WINDOW = [1989, 2015]\n"
        f"export const COLLEGES = {js(colleges)}\n"
        f"export const TEAMS = {js(teams)}\n"
        f"export const STEALS = {js(steals)}\n"
        f"export const PICK_CURVE = {js(curve)}\n"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
